In [1]:
!pip install selenium
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd
pd.set_option('display.max_columns', None) # 데이터프레임 컬럼 display

import warnings
warnings.filterwarnings('ignore') # 경고 무시

from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: selenium in c:\users\admin\appdata\roaming\python\python39\site-packages (4.4.3)
Requirement already satisfied: certifi>=2021.10.8 in c:\anaconda3\lib\site-packages (from selenium) (2021.10.8)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\admin\appdata\roaming\python\python39\site-packages (from selenium) (0.9.2)
Requirement already satisfied: trio~=0.17 in c:\users\admin\appdata\roaming\python\python39\site-packages (from selenium) (0.21.0)
Requirement already satisfied: urllib3[socks]~=1.26 in c:\anaconda3\lib\site-packages (from selenium) (1.26.9)
Requirement already satisfied: idna in c:\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: async-generator>=1.9 in c:\users\admin\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: cffi>=1.14 in c:\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.0)
Requirement already satisfied: sortedcontainers in c:\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: outcome in c:\users\admin\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: attrs>=19.2.0 in c:\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: sniffio in c:\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: pycparser in c:\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: wsproto>=0.14 in c:\users\admin\appdata\roaming\python\python39\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\anaconda3\lib\site-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\admin\appdata\roaming\python\python39\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.13.0)

In [12]:
# 반복문으로 각 url 출력
seasons = [f'0{num}' for num in range(14, 19)]
yymms = [
pd.date_range('2017-11', '2018-04', freq = 'M').strftime('%Y-%m').to_list(),
pd.date_range('2018-10', '2019-04', freq = 'M').strftime('%Y-%m').to_list(),
pd.date_range('2019-10', '2020-04', freq = 'M').strftime('%Y-%m').to_list(),
pd.date_range('2020-10', '2021-05', freq = 'M').strftime('%Y-%m').to_list(),
pd.date_range('2021-10', '2022-03', freq = 'M').strftime('%Y-%m').to_list()
]
# print(seasons)
# print(yymm)

for season, dates in zip(seasons, yymms) :
    for date in dates :
        url = f'https://www.kovo.co.kr/game/v-league/11110_schedule_list.asp?season={season}&team=&yymm={date}&r_round='
        print(url)

https://www.kovo.co.kr/game/v-league/11110_schedule_list.asp?season=014&team=&yymm=2017-11&r_round=
https://www.kovo.co.kr/game/v-league/11110_schedule_list.asp?season=014&team=&yymm=2017-12&r_round=
https://www.kovo.co.kr/game/v-league/11110_schedule_list.asp?season=014&team=&yymm=2018-01&r_round=
https://www.kovo.co.kr/game/v-league/11110_schedule_list.asp?season=014&team=&yymm=2018-02&r_round=
https://www.kovo.co.kr/game/v-league/11110_schedule_list.asp?season=014&team=&yymm=2018-03&r_round=
https://www.kovo.co.kr/game/v-league/11110_schedule_list.asp?season=015&team=&yymm=2018-10&r_round=
https://www.kovo.co.kr/game/v-league/11110_schedule_list.asp?season=015&team=&yymm=2018-11&r_round=
https://www.kovo.co.kr/game/v-league/11110_schedule_list.asp?season=015&team=&yymm=2018-12&r_round=
https://www.kovo.co.kr/game/v-league/11110_schedule_list.asp?season=015&team=&yymm=2019-01&r_round=
https://www.kovo.co.kr/game/v-league/11110_schedule_list.asp?season=015&team=&yymm=2019-02&r_round=
https://www.kovo.co.kr/game/v-league/11110_schedule_list.asp?season=015&team=&yymm=2019-03&r_round=

In [3]:
def get_result(driver) :
    html = driver.page_source
    soup = BeautifulSoup(html, 'html.parser')
    table = soup.find_all('table')

    team1 = pd.read_html(str(table))[0].reset_index(drop=False)
    
    date_selector = '#wrp_content > article.wrp_recentgame.wrp_result > table > tbody > tr > td:nth-child(3) > table > tbody > tr:nth-child(1) > td:nth-child(2)'
    date = soup.select_one(date_selector).get_text()
    
    return date

In [4]:
def get_result(driver) :
    html = driver.page_source
    soup = BeautifulSoup(html, 'html.parser')
    table = soup.find_all('table')
    result = pd.read_html(str(table))[1]
    
    return result

In [10]:
def c_frame(dtframe):
    df1 = dtframe.drop(2)
    df2 = pd.DataFrame(dtframe.iloc[2,1:]).T
    col_name = ['경기시간_1set', '경기시간_2set','경기시간_3set', '경기시간_4set', '경기시간_5set', '경기시간_total']
    df2 = df2.rename(columns={ df2.columns[i] : col_name[i] for i in range(6)})
    for idx in df2.columns:
        df1[idx] = df2.loc[2, idx]
    return df1

In [13]:
driver = webdriver.Chrome()
url = "https://www.kovo.co.kr/game/v-league/11110_schedule_list.asp?season=014&team=&yymm=2017-10&r_round="
driver.get(url)
time.sleep(2)

html = driver.page_source
soup = BeautifulSoup(html, 'html.parser')
table = soup.find_all('table')
df = pd.read_html(str(table))[0]
idx = df[df['구분'] == '여자'].index.to_list()
idx = [i + 1 for i in idx]

dfs = []

try :
    x_path = f'//*[@id="type1"]/div/table/tbody/tr[{idx[0]}]/td[10]/a[3]' # 상세결과 버튼
    cursor = driver.find_element(By.XPATH,x_path)
except :
    x_path = f'//*[@id="type1"]/div/table/tbody/tr[{idx[0]}]/td[10]/a[2]' # 상세결과 버튼
    cursor = driver.find_element(By.XPATH,x_path)
cursor.click()
time.sleep(1)

temp_df = get_result(driver)

team_result = c_frame(temp_df)

team_result

,여자부,1SET,2SET,3SET,4SET,5SET,TOTAL,경기시간_1set,경기시간_2set,경기시간_3set,경기시간_4set,경기시간_5set,경기시간_total
0,IBK기업은행,11,25,25,20,15,96,22 m,27 m,29 m,29 m,19 m,2h06m
1,흥국생명,25,23,22,25,13,108,22 m,27 m,29 m,29 m,19 m,2h06m

In [ ]:
driver = webdriver.Chrome()
url = "https://www.kovo.co.kr/game/v-league/11110_schedule_list.asp?season=014&team=&yymm=2017-10&r_round="
driver.get(url)
time.sleep(2)

In [22]:
driver = webdriver.Chrome()
driver.get(url)
time.sleep(2)

for season, dates in zip(seasons, yymms) :
    for date in dates :
        url = f'https://www.kovo.co.kr/game/v-league/11110_schedule_list.asp?season={season}&team=&yymm={date}&r_round='
        # 경기 스케줄을 데이터프레임으로 저장 후 여자 경기의 인덱스를 idx에 저장
        driver.get(url)
        html = driver.page_source
        soup = BeautifulSoup(html, 'html.parser')
        table = soup.find_all('table')
        df = pd.read_html(str(table))[0]
        idx = df[df['구분'] == '여자'].index.to_list()
        idx = [i + 1 for i in idx]

        dfs = []
        
        try :
            x_path = f'//*[@id="type1"]/div/table/tbody/tr[{idx[0]}]/td[10]/a[3]' # 상세결과 버튼
            cursor = driver.find_element(By.XPATH,x_path)
        except :
            x_path = f'//*[@id="type1"]/div/table/tbody/tr[{idx[0]}]/td[10]/a[2]' # 상세결과 버튼
            cursor = driver.find_element(By.XPATH,x_path)
        cursor.click()
        time.sleep(1)

        temp_df = get_result(driver)
        temp_df = c_frame(temp_df)
        team_result = team_result.append(temp_df)

team_result

,여자부,1SET,2SET,3SET,4SET,5SET,TOTAL,경기시간_1set,경기시간_2set,경기시간_3set,경기시간_4set,경기시간_5set,경기시간_total
0,IBK기업은행,11,25,25,20,15,96,22 m,27 m,29 m,29 m,19 m,2h06m
1,흥국생명,25,23,22,25,13,108,22 m,27 m,29 m,29 m,19 m,2h06m
0,IBK기업은행,11,25,25,20,15,96,NaN,NaN,NaN,NaN,NaN,NaN
1,흥국생명,25,23,22,25,13,108,NaN,NaN,NaN,NaN,NaN,NaN
2,경기시간,22 m,27 m,29 m,29 m,19 m,2h06m,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,IBK기업은행,25,25,25,0,0,75,26 m,29 m,33 m,0 m,0 m,1h28m
0,GS칼텍스,21,19,18,0,0,58,32 m,31 m,29 m,0 m,0 m,1h32m
1,한국도로공사,25,25,25,0,0,75,32 m,31 m,29 m,0 m,0 m,1h32m
0,GS칼텍스,25,25,25,0,0,75,26 m,28 m,24 m,0 m,0 m,1h18m
1,현대건설,21,18,16,0,0,55,26 m,28 m,24 m,0 m,0 m,1h18m

In [ ]:
print(get_result(driver))

In [27]:
team_result.tail(31)

,여자부,1SET,2SET,3SET,4SET,5SET,TOTAL,경기시간_1set,경기시간_2set,경기시간_3set,경기시간_4set,경기시간_5set,경기시간_total
0,KGC인삼공사,19,21,22,0,0,62,NaN,NaN,NaN,NaN,NaN,NaN
1,IBK기업은행,25,25,25,0,0,75,NaN,NaN,NaN,NaN,NaN,NaN
2,경기시간,26 m,29 m,33 m,0 m,0 m,1h28m,NaN,NaN,NaN,NaN,NaN,NaN
0,GS칼텍스,21,19,18,0,0,58,NaN,NaN,NaN,NaN,NaN,NaN
1,한국도로공사,25,25,25,0,0,75,NaN,NaN,NaN,NaN,NaN,NaN
2,경기시간,32 m,31 m,29 m,0 m,0 m,1h32m,NaN,NaN,NaN,NaN,NaN,NaN
0,GS칼텍스,25,25,25,0,0,75,NaN,NaN,NaN,NaN,NaN,NaN
1,현대건설,21,18,16,0,0,55,NaN,NaN,NaN,NaN,NaN,NaN
2,경기시간,26 m,28 m,24 m,0 m,0 m,1h18m,NaN,NaN,NaN,NaN,NaN,NaN
0,흥국생명,20,18,16,0,0,54,27 m,28 m,28 m,0 m,0 m,1h23m
1,한국도로공사,25,25,25,0,0,75,27 m,28 m,28 m,0 m,0 m,1h23m
0,IBK기업은행,25,25,25,0,0,75,26 m,27 m,24 m,0 m,0 m,1h17m
1,흥국생명,18,19,14,0,0,51,26 m,27 m,24 m,0 m,0 m,1h17m
0,IBK기업은행,25,25,19,25,0,94,25 m,24 m,29 m,22 m,0 m,1h40m
1,현대건설,21,15,25,17,0,78,25 m,24 m,29 m,22 m,0 m,1h40m
0,KGC인삼공사,22,20,25,25,13,105,26 m,24 m,23 m,26 m,18 m,1h57m
1,흥국생명,25,25,13,17,15,95,26 m,24 m,23 m,26 m,18 m,1h57m
0,KGC인삼공사,20,18,25,14,0,77,26 m,25 m,27 m,22 m,0 m,1h40m
1,GS칼텍스,25,25,20,25,0,95,26 m,25 m,27 m,22 m,0 m,1h40m
0,한국도로공사,21,20,25,27,15,108,28 m,29 m,33 m,37 m,21 m,2h28m
1,IBK기업은행,25,25,23,25,12,110,28 m,29 m,33 m,37 m,21 m,2h28m
0,흥국생명,30,17,20,0,0,67,39 m,26 m,28 m,0 m,0 m,1h33m
1,IBK기업은행,32,25,25,0,0,82,39 m,26 m,28 m,0 m,0 m,1h33m
0,GS칼텍스,24,20,14,0,0,58,31 m,28 m,27 m,0 m,0 m,1h26m
1,흥국생명,26,25,25,0,0,76,31 m,28 m,27 m,0 m,0 m,1h26m
0,KGC인삼공사,19,21,22,0,0,62,26 m,29 m,33 m,0 m,0 m,1h28m
1,IBK기업은행,25,25,25,0,0,75,26 m,29 m,33 m,0 m,0 m,1h28m
0,GS칼텍스,21,19,18,0,0,58,32 m,31 m,29 m,0 m,0 m,1h32m
1,한국도로공사,25,25,25,0,0,75,32 m,31 m,29 m,0 m,0 m,1h32m
0,GS칼텍스,25,25,25,0,0,75,26 m,28 m,24 m,0 m,0 m,1h18m
1,현대건설,21,18,16,0,0,55,26 m,28 m,24 m,0 m,0 m,1h18m